### ISSUE TITLE
RedisStrategy removed?

### ISSUE THREAD

**Issue by dathoangnd** [paul-phan/shopify-express-x#18]
Hi, thank you for maintaining this package.

But why you removed RedisStrategy, I think we should not use MemoryStrategy in production. Is there any reason behind this?

Thanks.

**Comment by paul-phan** [comment]
@dathoangnd The MemoryStrategy is only an example, you should write your own strategy and use it in the Shopify configs object with `shopStore` property:

`const shopify = shopifyExpress({
  shopStore: new YourStrategy(yourConfig),
  ...restOfConfig,
});`

**Comment by dathoangnd** [comment]
Thank you for your response.

By the way, not related to this issue, does this package handle authentication for already installed app? I mean, user open the app from Shopify dashboard, the afterAuth callback not fire. Do I need to handle this myself?

**Comment by paul-phan** [comment]
Yes, it should automatically handle authentication for the already installed app, you can checkout this file for more details: `https://github.com/paul-phan/shopify-express-x/blob/master/routes/shopifyAuth.js`
Just make sure you are using the correct session middleware for your express app and database.
